# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MVVM-Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift', '~> 3.0'
  pod 'RxCocoa', '~> 3.0'
  pod 'RxDataSources', '~> 2.0'
  pod 'RealmSwift', '~> 3.0'
  pod 'KRActivityIndicatorView'
  pod 'KRProgressHUD', '~> 3.0'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  # Pods for MVVM-Example

  target 'MVVM-ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVM-ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
