# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'MVVM-Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'RealmSwift'
  pod 'KRActivityIndicatorView'
  pod 'KRProgressHUD'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  # Pods for MVVM-Example

  target 'MVVM-ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVM-ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
